
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gcsfuse-rwx
provisioner: gcsfuse.csi.storage.gke.io
reclaimPolicy: Retain
volumeBindingMode: Immediate
allowVolumeExpansion: true
mountOptions:
  - implicit-dirs
