
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: airflow-web
  namespace: airflow
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      component: web
  endpoints:
  - port: web
    interval: 30s
    path: /admin/metrics
